Import Debian changes 1.9-3
batik (1.9-3) unstable; urgency=medium

  * Team upload.
  * Made the rhino and jython dependencies optional (Closes: #875322)
  * Removed the unused dependencies on libbsf-java, libcommons-io-java
    and libcommons-logging-java
  * Build with Maven instead of Ant
  * Build with the DH sequencer instead of CDBS
  * Standards-Version updated to 4.1.1
  * Switch to debhelper level 10

batik (1.9-2) unstable; urgency=medium

  * Fix "batik-1.9 causes FTBFS for freeplane due to changed
    artifacts/poms" Upstream poms assume maven build. Ant build bundles contents
    of batik-i18n.jar and batik-constants.jar into batik-util.jar. Use 
    debian/maven.rules to adjust for this. (Closes: #875322)

batik (1.9-1) unstable; urgency=medium

  * Team upload.
  * Moved the package to Git
  * Updated signing keys from https://www.apache.org/dist/xmlgraphics/batik/KEYS
  * Exclude jar files from documentation-sources 
  * Add repack script to remove non-free ICC profiles
  * New upstream (1.9) 
      + Fix "CVE-2017-5662: information disclosure vulnerability" Upstream claim
        BATIK-1139 is fixed in 1.9 (Closes: #860566)
  * Disable old patches, pending further investigation 
  * Get package building again
      +  maven-artifacts is no longer a target, explicitly add jars to 
         DEB_ANT_BUILD_TARGET
      +  Add debian/debian/libbatik-java.poms, call mh_install to install jars
         and poms, for closer alignment to other pkg-java packages
  * Fix spellings in debian/manpages/rasterizer.1
  * Remove redundant remove-js.patch
  * Fix "batik is crashing (libbatik-java)" by patching build.xml to specify
    classpaths as appropriate for Debian (Closes: #605063)
  * Update Standards-Version from 3.9.8 to 4.0.0 (no change required)
  * Update 06_fix_paths_in_policy_files.patch 
  * Remove bug805469.patch (fixed upstream 
    http://svn.apache.org/viewvc?view=revision&revision=1687506)
  * Update debian/copyright 
  * Remove unnecessary greater-than versioned dependencies from debian/control

batik (1.8-4) unstable; urgency=medium

  [ Jakub Adam ]
  * Team upload.
  * Fix versioned OSGi dependencies.
  * Fix repeating Breaks: in d/control.

  [ Mathieu Malaterre ]
  * Team upload.
  * Fix squiggle script crashes with a NoClassDefFoundError. Closes: #824113
  * Fix FOUserAgent - SVG graphic could not be built. Closes: #805469
  * Bump Std-Vers to 3.9.8, no changes needed

batik (1.8-3) unstable; urgency=medium

  [ Mathieu Malaterre ]
  * Team upload.
  * Fix compatibility issue. Closes: 794214

  [ Emmanuel Bourg ]
  * Removed the unused dependency on libavalon-framework-java

batik (1.8-2) experimental; urgency=medium

  * Team upload.
  * Fix truncated patch: d/p/06_fix_paths_in_policy_files.patch
  * Fix broken symlinks (Thanks to Jérôme Robert/debian-java)

batik (1.8-1) experimental; urgency=medium

  * Team upload.
  * New upstream. Closes: #792175
  * Refreshed patches, remove one applied upstream.
  * Prefer File-Excluded: syntax over new-upstream script

batik (1.7+dfsg-5) unstable; urgency=medium

  [ tony mancill ]
  * Team upload.
  * Update homepage URL to https://xmlgraphics.apache.org/batik/ in
    debian/control and debian/copyright. (Closes: #771539)
  * Add debian/patches/cve_2015_0250.patch to disable external XML entity
    resolution (information disclosure).  This addresses CVE-2015-0250.
    (Closes: #780897)

  [ Emmanuel Bourg ]
  * Replaced the Build-Id in the manifests with a constant value
    to make the build reproducible.

batik (1.7+dfsg-4) unstable; urgency=low

  * Team upload.
  [ Jakub Adam ]
  * Add OSGi metadata to JAR manifests.

  [ Markus Koschany ]
  * debian/rules: Set JAVA_HOME_DIRS to /usr/lib/jvm/default-java,
    build-depend on default-jdk and not on openjdk6-jdk |
    openjdk-7-jdk anymore. Fixes FTBFS with pbuilder-satisfydepends-classic.
    (Closes: #725461)
  * Bump Standards-Version to 3.9.4, no changes.
  * Bump compat level to 9 and require debhelper >= 9.
  * Use canonical VCS-URI.
  * Remove Michael Koch from Uploaders. (Closes: #653996)
  * libatik-java: Drop all jre/jdk dependencies. Recommend default-jre instead.
  * Run wrap-and-sort -sa
  * Add DEP-3 header to all patches.

batik (1.7+dfsg-3) unstable; urgency=low

  * Team upload.
  * Fix too strict Java JRE dependency.  (Closes: #678612)

batik (1.7+dfsg-2) unstable; urgency=low

  * Team upload.
  * Allow OpenJDK-7 as alternative to OpenJDK-6.
  * Remove old references to sun-java.
  * Add missing call to mh_clean in the clean rule.
  * Fix typo in manpage.

batik (1.7+dfsg-1) unstable; urgency=low

  * Provide a repackaged tarball stripping all binary jars (closes: #657244)
    - updated debian/new-upstream as a consequence 
  * Disable the installation of batik-js.jar, that wasn't built from sources 
    (it was a subset of rhino's js.jar)
  * Conforms to standards 3.9.3
  * Modernize a bit debian/copyright

batik (1.7-8) unstable; urgency=low

  * Fix FTBS with recent openjdk (closes: #643508)
  * Bump to newer standards version, no changes required

batik (1.7-7) unstable; urgency=low

  * Re-enable all patches that had mistakenly been disabled by switching to
    source format 3.0 (quilt) (closes: #604871)
  * Already conforms to standards 3.9.1

batik (1.7-6) unstable; urgency=low

  [ Vincent Fourmond ]
  * Really fix the dependency on java runtime to only pull headless
    runtimes

  [ Gabriele Giacone ]
  * Added Maven support
  * Standards-Version to 3.8.4
  * Source format 3.0 (quilt)

batik (1.7-5) unstable; urgency=low

  * Dropped the dependency on openjdk-6-jre, in profit for
    openjdk-6-jre-headless, so we won't pull the whole Gtk libraries just
    for using fop (closes: #551545).
  * Already conforms to standards 3.8.3
  * Removing Arnaud Vandyck from Uploaders as he did retire. Many thanks
    for your work on batik !

batik (1.7-4) unstable; urgency=low

  * Porting fixes from Ubuntu (1.7.dfsg-0ubuntu3) by Onkar Shinde
    <onkarshinde@ubuntu.com>:
    - add xml-apis-ext and js to classpath for debian/wrappers/squiggle
    - promote rhino to a Recommends, as squiggle depends on it
    - debian/patches/06_fix_paths_in_policy_files.patch to fix the paths
      of the security policy files
  * This finally makes squiggle work for Debian ! (closes: #499852)
    Many thanks again to Onkar...

batik (1.7-3) unstable; urgency=low

  [ Onkar Shinde ]
  * debian/rules
    - Use DEB_UPSTREAM_VERSION at all places.
    - Add symlinks batik-<version>.jar and batik.jar pointing to
      batik-all-<version>.jar. (Closes: #522340)
  * debian/control
    - Add myself to 'Uploaders'.

  [ Vincent Fourmond ]
  * Changed section to java, what currently is in the archive
  * Already conforms to standard 3.8.1
  * Bumped debhelper compatibility level to 5, and bumped Build-depends
    accordingly

batik (1.7-2) unstable; urgency=low

  * Adding xmlgraphics-commons-1.2 and xml-apis-ext to the jars for
    the build + corresponding build-deps
  * Added Vcs-* fields

  [ Sylvestre Ledru ]
  * Build class version 49 (instead of 50)

  [ Vincent Fourmond ]
  * Minor updates to the debian/copyright file 
  * It seems time has come for an upload to unstable...
  * Adding ${misc:Depends} for potential debhelper-induced dependencies
  * Tweaking rasterizer.1 to avoid unbreakable lines

batik (1.7-1) experimental; urgency=low

  * New upstream release (Closes: #417888, #490556)
  * Switched to using java-wrappers for executables; dropping the 
    /usr/lib/java/wrappers.sh script
  * Switched debian/copyright to a machine-readable format
  * Added ANT_OPTS to fix the compiler out of memory problem
  * Removing 02_fix_jar_target, no longer applicable
  * Removing 01_build_xml, as the created target (pdf-transcoder) cannot
    be built anymore
  * Fixed JAVA_HOME_DIRS so it can build with Sun's java 5
  * Strip the full text of the Apache-2.0 license, as it now is
    in the common licenses
  * Switch to openjdk-6-jdk for building (closes: #397562)
  * Several tweaks in debian/rules to build and install all the jars,
    based on a patch by Sylvestre Ledru <sylvestre.ledru@inria.fr>
  * Now depends also on libxml-commons-external-java for SVG parsing
  * Conforms to standards 3.8.0
  * Updated rasterizer.sh to work with libxml-commons-external-java
    and openjdk (closes: #490621)
  * Move wrapper scripts to debian/wrappers, updating debian/rules 
    accordingly
  * Recommend fop for PDF output of rasterizer
  * Removed README.Debian-source: we don't add the fop sources anymore
    as those are already packaged in the fop debian package
  * Uploading to experimental, as there are potentially much too many
    disruptive changes to this package.

batik (1.6-4) unstable; urgency=low

  [ Mark Howard ]
  * debian/watch: added.

  [ Vincent Fourmond ]
  * Created a /usr/lib/java/wrappers.sh for the various programs
    provided by libbatik-java, to make them work in more various
    environments.
  * Manual pages for svgpp, rasterizer, squiggle and ttf2svg
    (Closes: #458021)
  * rasterizer now launches by default with -scriptSecurityOff so it
    works again (Closes: #413103). Added an option to turn security back on.
  * Comply with policy 3.7.3
  * Changed build-deps to sun-j2sdk1.4, to reflect the current make-jpkg
    output.

batik (1.6-3) unstable; urgency=low

  * Add wrapper scripts (rasterizer.sh squiggle.sh svgpp.sh ttf2svg.sh)
    to start batik applications.  Install them without the .sh prefix in
    /usr/bin/.  (Closes: #152180)
  * Removed build dependency on libgnujaxp-java (Closes: #385293).
  * Build-Depends on debhelper and cdbs (instead of Build-Depends-Indep).
  * Build-Depends-Indep on java-gcj-compat-dev.
  * Updated Standards-Version to 3.7.2.
  * Added myself to Uploaders.

batik (1.6-2) unstable; urgency=low

  * Re-Introduce lost link batik.jar and add 02_fix_jar_target.patch 
    to fix library content (closes: #334878)
  * Thighten depends on avalon-framework (closes: #335883)
  * Corrected README.Debian

batik (1.6-1) unstable; urgency=low

  * New upstream release
    + Updated copyright to Apache 2.0 License
  * libant1.6-java to ant transition
  * Use JAVA_HOME dirs as generated by java-package (closes: #306639)
  * Include, build and ship the pdf-transcoder from fop CVS (closes: #327354)
    + See README.Debian-source for details about the transcoder source
    + Added build-deps and depends on libavalon-framework-java, 
      libcommons-io-java and libcommons-logging-java for the pdf-transcoder
    + Patched build.xml to call the pdf-transcoder build target
  * Removed Ola and Stephan from uploaders
  * Extended description a little bit
  * Standards-Version 3.6.2 (no changes)  

batik (1.5.1-1) unstable; urgency=low

  * New upstream release - security fix [CAN-2005-0508] (closes: #288009)
  * Added rhino as build dependency
  * Added rhino to Suggests
  * Switched to jdk modern compiler because jikes fails
  * Updated README.Debian explaining why built with non-free jdk
  * Updated standards version to 3.6.1 - no changes
  * avdyk: I added Wolfgang to the uploaders

batik (1.5final-3) unstable; urgency=low

  * expand SVG in description (closes: #173105).

batik (1.5final-2) unstable; urgency=low

  * added the dependency and the path to j2sdk1.3 to build batik (closes:
    #192539). You got to know that I have not been able to build batik
    with j2sdk1.3. I've been obliged to build it with IBMJDK1.4.1.
  * added gnujaxp as a dependency and in the classpath (closes: #192542)

batik (1.5final-1) unstable; urgency=low

  * New upstream release
  * Build system is now CDBS
  * Added build-dependencies libxalan2-java and libbsf-java
  * Changed Stefan Gybas email
  * j2sdk to build and j2re to run because of swing
  * Debian Java Maintainers is now the new maintainer, added Ola Lundqvist
    <opal@debian.org>, Takashi Okamoto <tora@debian.org>, Stefan Gybas
    <sgybas@debian.org>, Arnaud Vandyck <avdyk@debian.org> as uploaders

batik (1.5beta2-4) unstable; urgency=low

  * Renamed the batik jar file, closes: #171327.

batik (1.5beta2-3) unstable; urgency=low

  * Jars in /usr/share/java not in /usr/share/java/lib, closes: #170791.

batik (1.5beta2-2) unstable; urgency=low

  * New maintainer.
  * Fixed dependencies, closes: #158221.
  * Fixed build problem.
  * Added two other people as co-maintainers.
  * Fixed so that building wont take that long time if -nc option is used.
  * Now can use kaffe instead of j2sdk. Workaround for a bug in kaffe.
    On the other hand it seems not like the classic compiler so I still have
    to set that damn JAVA_HOME to the j2sdk...

batik (1.5beta2-1) unstable; urgency=low

  * Initial Upload (Closes: #149676)